In [3]:
import pandas as pd
data=pd.read_csv('/content/weight-height.csv')
display(data)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

in here the dataset csv file show shows how that we can read  for that we use the pd.read_csv() fungtion

In [4]:
data.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

 given dataset we are taken first 5 values . its
already the defalted value is 5 . we can give more values then shows how many values have

In [5]:
data.tail()

      Gender     Height      Weight
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

given dataset are taken last 5 values . its already the defaulted value is 5 . we can give more values then shows how many values have

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  10000 non-null  object
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB

 in here we can clearly see that dataset .info updates flot type
digit type int type info .in here geving these kind of information

In [7]:
data.isnull()

      Gender  Height  Weight
0      False   False   False
1      False   False   False
2      False   False   False
3      False   False   False
4      False   False   False
...      ...     ...     ...
9995   False   False   False
9996   False   False   False
9997   False   False   False
9998   False   False   False
9999   False   False   False

[10000 rows x 3 columns]

 here we can seeing how many null values in these dataset
in here no null vales is here

In [8]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

here we can see the dataset duplicated values and in these dataset are no duplicate value

In [9]:
data.drop_duplicates()

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

in here these function shows how to remove the duplicated values

In [10]:
data.describe()

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

in here the data described in that standered deviation,meanvalues,count,and some persentages 25%,50%,75%, and max values

these are some fungtions to clearly discribe the data features and then we can easily analysis the dataset
describe ,info, nullvales,head and tail these are the basic fungtions forananlysing the dataset